package domain

type OverallResults struct {
	Id                  int     `json:"id" db:"id"`
	Name                string  `json:"name" db:"name"`
	OverallDepth        float64 `json:"overall_depth" db:"overall_depth"`
	Weight              float64 `json:"weight" db:"weight"`
}

type SteelArgumentsDesignResults struct {
	Pt                  float64 `json:"pt" db:"pt"`
	Pc                  float64 `json:"pc" db:"pc"`
	Mcx                 float64 `json:"mcx" db:"mcx"`
	Mcy                 float64 `json:"mcy" db:"mcy"`
	Vcx                 float64 `json:"vcx" db:"vcx"`
	Vcy                 float64 `json:"vcy" db:"vcy"`
	Pratio              float64 `json:"pratio" db:"pratio"`
	MxRatio             float64 `json:"mx_ratio" db:"mx_ratio"`
	MyRatio             float64 `json:"my_ratio" db:"my_ratio"`
	VxRatio             float64 `json:"vx_ratio" db:"vx_ratio"`
	VyRatio             float64 `json:"vy_ratio" db:"vy_ratio"`
	Combined            float64 `json:"combined" db:"combined"`
	KLr                 float64 `json:"k_lr" db:"k_lr"`
}

type CreateSteelDesignArguments struct {
	ID                    int     `json:"id" db:"id"`
	Name                  string  `json:"name" db:"name"`
	Analysis              string  `json:"analysis" db:"analysis"`
	Method                string  `json:"method" db:"method"`
	Units                 string  `json:"units" db:"units"`
	TensileFactor         float64 `json:"tensile_factor" db:"tensile_factor"`
	CompressFactor        float64 `json:"compress_factor" db:"compress_factor"`
	BendingFactor         float64 `json:"bending_factor" db:"bending_factor"`
	ShearFactor           float64 `json:"shear_factor" db:"shear_factor"`
	Vx                    float64 `json:"vx" db:"vx"`
	Vy                    float64 `json:"vy" db:"vy"`
	Mx                    float64 `json:"mx" db:"mx"`
	My                    float64 `json:"my" db:"my"`
	P                     float64 `json:"p" db:"p"`
	Lb                    float64 `json:"lb" db:"lb"`
	Lx                    float64 `json:"lx" db:"lx"`
	Kx                    float64 `json:"kx" db:"kx"`
	Ly                    float64 `json:"ly" db:"ly"`
	Ky                    float64 `json:"ky" db:"ky"`
	LLT                   float64 `json:"llt" db:"llt"`
	Cbx                   float64 `json:"cbx" db:"cbx"`
	Cby                   float64 `json:"cby" db:"cby"`
	SRc                   float64 `json:"s_rc" db:"s_rc"`
	SRt                   float64 `json:"s_rt" db:"s_rt"`
	ModE                  float64 `json:"mod_e" db:"mod_e"`
	YieldStr              float64 `json:"yield_str" db:"yield_str"`
	UltStr                float64 `json:"ult_str" db:"ult_str"`
	Shape                 string  `json:"shape" db:"shape"`
	SteelSections_t_f     string  `json:"steel_sections_t_f" db:"steel_sections_t_f"`
	SteelSections_w       string  `json:"steel_sections_w" db:"steel_sections_w"`
	SteelSections_a       string  `json:"steel_sections_a" db:"steel_sections_a"`
	SteelSections_d       string  `json:"steel_sections_d" db:"steel_sections_d"`
	SteelSections_ddet    string  `json:"steel_sections_ddet" db:"steel_sections_ddet"`
	SteelSections_ht      string  `json:"steel_sections_ht" db:"steel_sections_ht"`
	SteelSections_h       string  `json:"steel_sections_h" db:"steel_sections_h"`
	SteelSections_od      string  `json:"steel_sections_od" db:"steel_sections_od"`
	SteelSections_bf      string  `json:"steel_sections_bf" db:"steel_sections_bf"`
	SteelSections_bfdet   string  `json:"steel_sections_bfdet" db:"steel_sections_bfdet"`
	SteelSections_bhss    string  `json:"steel_sections_bhss" db:"steel_sections_bhss"`
	SteelSections_b       string  `json:"steel_sections_b" db:"steel_sections_b"`
	SteelSections_id      string  `json:"steel_sections_id" db:"steel_sections_id"`
	SteelSections_tw      string  `json:"steel_sections_tw" db:"steel_sections_tw"`
	SteelSections_twdet   string  `json:"steel_sections_twdet" db:"steel_sections_twdet"`
	SteelSections_twdet_2 string  `json:"steel_sections_twdet_2" db:"steel_sections_twdet_2"`
	SteelSections_tf      string  `json:"steel_sections_tf" db:"steel_sections_tf"`
	SteelSections_tfdet   string  `json:"steel_sections_tfdet" db:"steel_sections_tfdet"`
	SteelSections_th      string  `json:"steel_sections_th" db:"steel_sections_th"`
	SteelSections_tnom    string  `json:"steel_sections_tnom" db:"steel_sections_tnom"`
	SteelSections_tdes    string  `json:"steel_sections_tdes" db:"steel_sections_tdes"`
	SteelSections_kdes    string  `json:"steel_sections_kdes" db:"steel_sections_kdes"`
	SteelSections_kdet    string  `json:"steel_sections_kdet" db:"steel_sections_kdet"`
	SteelSections_k1      string  `json:"steel_sections_k1" db:"steel_sections_k1"`
	SteelSections_x       string  `json:"steel_sections_x" db:"steel_sections_x"`
	SteelSections_y       string  `json:"steel_sections_y" db:"steel_sections_y"`
	SteelSections_eo      string  `json:"steel_sections_eo" db:"steel_sections_eo"`
	SteelSections_xp      string  `json:"steel_sections_xp" db:"steel_sections_xp"`
	SteelSections_yp      string  `json:"steel_sections_yp" db:"steel_sections_yp"`
	SteelSections_bf_2tf  string  `json:"steel_sections_bf_2_tf" db:"steel_sections_bf_2_tf"`
	SteelSections_b_t     string  `json:"steel_sections_b_t" db:"steel_sections_b_t"`
	SteelSections_b_tdes  string  `json:"steel_sections_b_tdes" db:"steel_sections_b_tdes"`
	SteelSections_h_tw    string  `json:"steel_sections_h_tw" db:"steel_sections_h_tw"`
	SteelSections_h_tdes  string  `json:"steel_sections_h_tdes" db:"steel_sections_h_tdes"`
	SteelSections_d_t     string  `json:"steel_sections_d_t" db:"steel_sections_d_t"`
	SteelSections_ix      string  `json:"steel_sections_ix" db:"steel_sections_ix"`
	SteelSections_zx      string  `json:"steel_sections_zx" db:"steel_sections_zx"`
	SteelSections_sx      string  `json:"steel_sections_sx" db:"steel_sections_sx"`
	SteelSections_rx      string  `json:"steel_sections_rx" db:"steel_sections_rx"`
	SteelSections_iy      string  `json:"steel_sections_iy" db:"steel_sections_iy"`
	SteelSections_zy      string  `json:"steel_sections_zy" db:"steel_sections_zy"`
	SteelSections_sy      string  `json:"steel_sections_sy" db:"steel_sections_sy"`
	SteelSections_ry      string  `json:"steel_sections_ry" db:"steel_sections_ry"`
	SteelSections_iz      string  `json:"steel_sections_iz" db:"steel_sections_iz"`
	SteelSections_rz      string  `json:"steel_sections_rz" db:"steel_sections_rz"`
	SteelSections_sz      string  `json:"steel_sections_sz" db:"steel_sections_sz"`
	SteelSections_j       string  `json:"steel_sections_j" db:"steel_sections_j"`
	SteelSections_cw      string  `json:"steel_sections_cw" db:"steel_sections_cw"`
	SteelSections_c       string  `json:"steel_sections_c" db:"steel_sections_c"`
	SteelSections_wno     string  `json:"steel_sections_wno" db:"steel_sections_wno"`
	SteelSections_sw1     string  `json:"steel_sections_sw_1" db:"steel_sections_sw_1"`
	SteelSections_sw2     string  `json:"steel_sections_sw_2" db:"steel_sections_sw_2"`
	SteelSections_sw3     string  `json:"steel_sections_sw_3" db:"steel_sections_sw_3"`
	SteelSections_qf      string  `json:"steel_sections_qf" db:"steel_sections_qf"`
	SteelSections_qw      string  `json:"steel_sections_qw" db:"steel_sections_qw"`
	SteelSections_ro      string  `json:"steel_sections_ro" db:"steel_sections_ro"`
	SteelSections_hfc     string  `json:"steel_sections_hfc" db:"steel_sections_hfc"`
	SteelSections_tan_a   string  `json:"steel_sections_tan_a" db:"steel_sections_tan_a"`
	SteelSections_iw      string  `json:"steel_sections_iw" db:"steel_sections_iw"`
	SteelSections_za      string  `json:"steel_sections_za" db:"steel_sections_za"`
	SteelSections_zb      string  `json:"steel_sections_zb" db:"steel_sections_zb"`
	SteelSections_zc      string  `json:"steel_sections_zc" db:"steel_sections_zc"`
	SteelSections_wa      string  `json:"steel_sections_wa" db:"steel_sections_wa"`
	SteelSections_wb      string  `json:"steel_sections_wb" db:"steel_sections_wb"`
	SteelSections_wc      string  `json:"steel_sections_wc" db:"steel_sections_wc"`
	SteelSections_swa     string  `json:"steel_sections_swa" db:"steel_sections_swa"`
	SteelSections_swb     string  `json:"steel_sections_swb" db:"steel_sections_swb"`
	SteelSections_swc     string  `json:"steel_sections_swc" db:"steel_sections_swc"`
	SteelSections_sza     string  `json:"steel_sections_sza" db:"steel_sections_sza"`
	SteelSections_szb     string  `json:"steel_sections_szb" db:"steel_sections_szb"`
	SteelSections_szc     string  `json:"steel_sections_szc" db:"steel_sections_szc"`
	SteelSections_rts     string  `json:"steel_sections_rts" db:"steel_sections_rts"`
	SteelSections_ho      string  `json:"steel_sections_ho" db:"steel_sections_ho"`
	SteelSections_pa      string  `json:"steel_sections_pa" db:"steel_sections_pa"`
	SteelSections_pa2     string  `json:"steel_sections_pa_2" db:"steel_sections_pa_2"`
	SteelSections_pb      string  `json:"steel_sections_pb" db:"steel_sections_pb"`
	SteelSections_pc      string  `json:"steel_sections_pc" db:"steel_sections_pc"`
	SteelSections_pd      string  `json:"steel_sections_pd" db:"steel_sections_pd"`
	SteelSections_t       string  `json:"steel_sections_t" db:"steel_sections_t"`
	SteelSections_wgi     string  `json:"steel_sections_wgi" db:"steel_sections_wgi"`
	SteelSections_wgo     string  `json:"steel_sections_wgo" db:"steel_sections_wgo"`
}
